# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use Ubuntu 14.04 Trusty Tahr 64-bit as our operating system
  config.vm.box = "ubuntu/trusty64"

  # Configurate the virtual machine to use 2GB of RAM
  config.vm.provider :virtualbox do |vb|
    vb.name = "RailsBox"
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  # Forward the Rails server default port to the host
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  # Use Chef Solo to provision our virtual machine
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = ["cookbooks"]

    chef.add_recipe "apt"
    chef.add_recipe "build-essential"
    chef.add_recipe "nodejs"
    chef.add_recipe "ruby_build"
    chef.add_recipe "rbenv::user"
    chef.add_recipe "rbenv::vagrant"
    chef.add_recipe "vim"
    chef.add_recipe "git"
    chef.add_recipe "postgresql"
    chef.add_recipe "ngix"
    chef.add_recipe "redis"

    chef.json = {
      rbenv: {
        user_installs: [{
          user: 'vagrant',
          rubies: ["2.2.1"],
          global: "2.2.1",
          gems: {
            "2.2.1" => [
              { name: "bundler" },
              { name: "rails" }
            ]
          }
        }]
      },
      redis: {
        bind: "127.0.0.1",
        port: "6379",
        config_path: "/etc/redis/redis.conf",
        daemonize: "yes",
        timeout: "300",
        loglevel: "notice"
      },
      nginx: {
        dir: "/etc/nginx",
        log_dir: "/var/log/nginx",
        binary: "/usr/sbin/nginx",
        user: "www-data",
        init_style: "runit",
        pid: "/var/run/nginx.pid",
        worker_connections: "1024"
      },
    }
  end
end
